# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R_CMD_Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  R_CMD_Check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r-version }})
    
    strategy:
      matrix:
        config:
          - { os: macOS-latest, r-version: "release" }
          - { os: windows-latest, r-version: "release" }
          - { os: ubuntu-22.04, r-version: "release" }
          - { os: ubuntu-latest, r-version: "release"}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          use-public-rspm: true
          
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"all"' # do not install suggests
          extra-packages: any::rcmdcheck, any::rmarkdown, any::markdown, local::.
          needs: check
          error-on: '"error"'
        
      - name: Check package
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"'
